apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gmqm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-gmqm@sha256:2ee1b29d851eec083b792487307cb6e5c72790b5a31c4319ce6d46d43de12f55
        name: my-nodejs
        resources: {}
status: {}
